DROP SEQUENCE LOGINSEQ;
DROP TABLE LOGIN;

CREATE SEQUENCE LOGINSEQ;

CREATE TABLE LOGIN(
	NUM NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	ID VARCHAR2(500) NOT NULL,
	PASSWORD VARCHAR2(500) NOT NULL,
	PHONENUMBER VARCHAR2(1000) NOT NULL,
	COMEDATE DATE NOT NULL
);

INSERT INTO LOGIN(NUM,WRITER, ID, PASSWORD, PHONENUMBER, COMEDATE)
VALUES(LOGINSEQ.NEXTVAL,'배유진', 'ADMIN1234' , 'ADMIN1234', '01034533683' ,SYSDATE);

SELECT NUM, WRITER, ID, PASSWORD, PHONENUMBER, COMEDATE
FROM LOGIN
ORDER BY NUM DESC;