CREATE TABLE TEST(
	
	RN NUMBER PRIMARY KEY,
	NAME VARCHAR2(10) 

);

SELECT * FROM TEST;

INSERT INTO TEST VALUES( 1, 'ZZANG' );
INSERT INTO TEST VALUES (2, 'BAE');
INSERT INTO TEST VALUES (3, 'KYU');
INSERT INTO TEST VALUES (4, 'BIGPIG');
INSERT INTO TEST VALUES (5, 'DJ');
INSERT INTO TEST VALUES (6, 'DH');
INSERT INTO TEST VALUES (7, 'HI');
INSERT INTO TEST VALUES (8, 'KH');
INSERT INTO TEST VALUES (9, 'Q');
INSERT INTO TEST VALUES (10, 'CLASS');
INSERT INTO TEST VALUES (11, 'TT');
INSERT INTO TEST VALUES (12, 'TTT');
INSERT INTO TEST VALUES(13, 'BTS');
INSERT INTO TEST VALUES (14, 'TTTG');
INSERT INTO TEST VALUES (15, 'EXO');
INSERT INTO TEST VALUES (16, 'HOME');


SELECT ROWNUM AS RNUM, A.RN, A.NAME FROM(
	SELECT RN, NAME
	FROM TEST 
	ORDER BY RN DESC
) A

SELECT ROWNUM AS RNUM, A.RN, A.NAME
FROM 
(SELECT RN, NAME FROM TEST ORDER BY RN ) A
WHERE ROWNUM BETWEEN 11 AND 20

SELECT COUNT(*) FROM TEST;



--SEQ 이후는 몇페이지부터 
--ROWNUM  이후는 몇개 잘라서 넣어준다는 것
SELECT RN, NAME
FROM (SELECT SEQ, RN, NAME FROM 
	(SELECT ROWNUM AS SEQ, RN, NAME
		FROM (SELECT * FROM TEST ORDER BY RN DESC)
	)
	WHERE SEQ >= (5-5)*3
)WHERE ROWNUM <= 3;

SELECT COUNT(*) FROM TEST;


