DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBERBOARD;

CREATE SEQUENCE MEMBERSEQ;

--번호, 이름, 나이, 성별, 지역, 직업, 전화번호, 이메일
CREATE TABLE MEMBERBOARD(

	MNO NUMBER PRIMARY KEY,
	MNAME VARCHAR2(100) NOT NULL,
	MAGE NUMBER NOT NULL,
	MGENDER VARCHAR2(2) CHECK(MGENDER IN ('M', 'F')) NOT NULL,
	MLOCATION VARCHAR2(300),
	MJOB VARCHAR2(100),
	MTEL VARCHAR2(20),
	MEMAIL VARCHAR2(100)

);


INSERT INTO MEMBERBOARD
VALUES (MEMBERSEQ.NEXTVAL, '관리자', 100, 'M', '경기도 수원시', '관리자', '010-1111-1111', 'ADMIN@MEMBER.COM');

SELECT MNO, MNAME, MAGE, MGENDER, MLOCATION, MJOB, MTEL, MEMAIL
FROM MEMBERBOARD;




















