DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBOARD;

CREATE SEQUENCE MDBOARDSEQ;

--번호, 작성자, 제목, 내용, 작성일
CREATE TABLE MDBOARD(
	
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL

);

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL, '관리자', 'TEST 글 입니다', 'Test1234', SYSDATE);

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL, '홍길동', '지나가던 사람', '지나감', SYSDATE);

INSERT INTO MDBOARD
VALUES(MDBOARDSEQ.NEXTVAL, '리눅스 토발즈', '리눅스 많이 사랑해주새요', 'CENTOS', SYSDATE);


SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM MDBOARD
ORDER BY SEQ DESC;
