DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

-- 글 번호 그룹번호 그룹순서 제목공백 제목 내용 작성자 장성일
CREATE TABLE ANSWERBOARD(

	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

--1번 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0,
'첫번째 글 입니다' , '첫번째 글 내용', '관리자', SYSDATE);

--2번 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '두번째 글 입니다'
, '두번째 글 내용', '이동헌', SYSDATE);

--1번 글에 답변 달기
--지금 내가 답변 달려고 하는 그룹 번호와 값이 같아야한다(부모글과 같은 번호이면서)
--부모의 글 번호에 + 1 해줘야한다(부모글의 순서보다 하나 커야한다-내가 쓴 답변글이 가장 위로 올라오게 하고 싶어서), 얘 뒤에 내가 작성하고자 하는 것보다 더 큰 것들을 찾아서 +1을 해주고 내 글을 쓸 것이다
--title tab 도 부모 + 1
INSERT INTO ANSWERBOARD
VALUES(
BOARDNOSEQ.NEXTVAL, 
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
(SELECT GROUPSEQ + 1 FROM ANSWERBOARD WHERE BOARDNO = 1),
(SELECT TITLETAB + 1 FROM ANSWERBOARD WHERE BOARDNO = 1),
'RE:1번 글에 대한 답변', '답변 1', '답변자', SYSDATE
);

--답변 1에 대한 답변
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO= 3),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 3) + 1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 3) + 1,
	'1번 답변 1에 대한 답변', '답변 1-1', '답변자', SYSDATE
);

--다시 1번 글에 답변 달기
--같은 그룹이면서, 그룹 순서가 더 큰것들을 찾아서 다 +1을 해준다(1번 글과 같은 그룹이면서 1번 글의 그룹 순서보다 더 큰 글들의 그룹 손서를 +1해준다)
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1 WHERE  GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)


--1번 글에 대한 답변 글 insert
INSERT INTO ANSWERBOARD
VALUES (
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
	(SELECT TITLETAB + 1 FROM ANSWERBOARD WHERE BOARDNO=1),
	'RE:...', '답변 어렵다', '답변자', SYSDATE
);


SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, TITLE, CONTENT, WRITER, REGDATE FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSEQ;

