DROP SEQUENCE CALBOARDSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;

--번호, 아이디, 제목, 내용, 일정, 작성일
CREATE TABLE CALBOARD(
	
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL

);

SELECT SEQ, ID, TITLE, CONTENT , MDATE, REGDATE
FROM CALBOARD;