DROP SEQUENCE CALBOARDSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;

--번호, 아이디, 제목, 내용, 일정, 작성일
CREATE TABLE CALBOARD(
	
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL

);

--ROW_NUMBER() OVER(PARTITION BY ?? ORDER BY !!) : 일별 그룹인 것이다~(ROW_NUM이 일별로 짤린다)
--!!로 ORDER BY, ?? 로 GROUP BY 해서, GROUP 별 ROWNUM 만들어 준다

SELECT * FROM
(
SELECT (ROW_NUMBER() OVER (PARTITION BY SUBSTR(MDATE, 1, 8) ORDER BY MDATE )) RN,
SUBSTR(MDATE, 1, 8),
SUBSTR(MDATE, 1, 6),
SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM CALBOARD
WHERE ID='kh' AND SUBSTR(MDATE, 1, 6) = '202008'
)
WHERE RN BETWEEN 1 AND 3;

SELECT SEQ, ID, TITLE, CONTENT , MDATE, REGDATE
FROM CALBOARD;