DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;


--글 번호, 그룹버, 그룹순서, 제목공백, 삭제여부(Y/N)
-- 제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERBOARD(

	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT PKNO PRIMARY KEY(BOARDNO),
	CONSTRAINT CHKDELE CHECK (DELFLAG IN ('Y', 'N'))
	
);

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSEQ;

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE FROM ANSWERBOARD WHERE BOARDNO = 1;