DROP TABLE X;
DROP TABLE S;
DROP TABLE M;

CREATE TABLE M
(M1 CHAR(6), M2 VARCHAR(10));
CREATE TABLE S
(S1 CHAR(6), S2 VARCHAR(10));
CREATE TABLE X
(X1 CHAR(6), X2 VARCHAR(10));

INSERT INTO M VALUES('A','1');
INSERT INTO M VALUES('B','1');
INSERT INTO M VALUES('C','3');
INSERT INTO M VALUES(NULL, '3');

INSERT INTO S VALUES('A','X');
INSERT INTO S VALUES('B','Y');
INSERT INTO S VALUES(NULL, 'Z');

INSERT INTO X VALUES('A','DATA');
COMMIT;












SELECT * FROM X;
SELECT * FROM M;
SELECT * FROM S;

--INNER JOIN(ANSI)
SELECT * FROM M INNER JOIN S ON M1=S1;

--INNER JOIN(ORACLE)
SELECT * FROM M, S
WHERE M.M1 = S.S1;

--CROSS JOIN
SELECT * FROM M CROSS JOIN S;
SELECT * FROM M, S;

--OUTER JOIN
--LEFT OUTER JOIN
SELECT * FROM M LEFT OUTER JOIN S ON M1 = S1;
--LEFT OUTER JOIN은 오른쪽에 (+)를 붙여준다
--같은 테이블이 아닌 경우 어떤 테이블인지 명시 해줘야한다
SELECT * FROM M, S WHERE M.M1 = S.S1(+);


--RIGHT OUTER JOIN
SELECT * FROM M RIGHT OUTER JOIN S ON M1 = S1;
SELECT * FROM M, S WHERE M.M1(+) = S.S1;

--------------------------------------

--EMP 과 DEPT 를 INNER JOIN
--ON을 쓰면 양쪽 컬럼이 같이 나온다
SELECT * FROM EMP 
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

--별칭 사용 가능
SELECT * FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

--USING : 앞에 있는 컬럼과 뒤의 컬럼이 같을 때 사용
-- 두개를 비교해서 하나로 합쳐준다
SELECT * FROM EMP E
INNER JOIN DEPT D
USING(DEPTNO);

--NONEQUV JOIN
--ANSI
SELECT ENAME, SAL, GRADE
FROM EMP JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL;

--ORACLE
SELECT ENAME, SAL, GRADE
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL;

--SELF JOIN
SELECT 사원.EMPNO, 사원.ENAME , 관리자.EMPNO, 관리자.ENAME
FROM EMP 사원, EMP 관리자
WHERE 사원.MGR = 관리자.EMPNO;




