DROP SEQUENCE MYSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYSEQ;
CREATE TABLE MYBOARD(
	
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL

);

INSERT INTO MYBOARD
VALUES (MYSEQ.NEXTVAL, '愿�由ъ옄' , '�삤�뒛�룄 �뀒�뒪�듃' , '�뀒�뒪�듃湲� �엯�땲�떎', SYSDATE);

SELECT MYNO, MYNAME, MYCONTENT, MYDATE
FROM MYBOARD;