DROP SEQUENCE MYSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYSEQ;
CREATE TABLE MYBOARD(
	
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL

);

INSERT INTO MYBOARD
VALUES (MYSEQ.NEXTVAL, '관리자' , '오늘도 테스트' , '테스트글 입니다', SYSDATE);

SELECT MYNO, MYNAME, MYCONTENT, MYDATE
FROM MYBOARD;